-- MEG-EAF V2 — Dashboard Access Gateway
-- Dashboard UVN: v2026.09.04-19:30
-- Applies to dashboard/app-access layer only. Existing MEG-EAF V2 form/LOEC identity remains unchanged.
-- Run AFTER migration 006 (V1/V2 permission separation) and later current migrations.

begin;

-- ---------------------------------------------------------------------------
-- 1) Add dashboard/app-access flags to the authoritative V2 permission row.
-- ---------------------------------------------------------------------------
alter table public.eaf_v2_staff_permissions
  add column if not exists can_access_apply boolean not null default false,
  add column if not exists can_access_hr boolean not null default false,
  add column if not exists can_access_jd_manual boolean not null default false,
  add column if not exists can_access_hr_law boolean not null default false;

-- Preserve existing HR users: anyone who already had a meaningful V2 HR permission
-- continues to be able to enter HR after the gateway is introduced.
update public.eaf_v2_staff_permissions
set can_access_hr = true
where coalesce(is_admin,false)
   or coalesce(is_super_admin,false)
   or coalesce(can_view_applications,false)
   or coalesce(can_view_only,false)
   or coalesce(can_edit_office_use,false)
   or coalesce(can_generate_letter,false)
   or coalesce(can_change_status,false)
   or coalesce(can_delete,false)
   or coalesce(can_view_summary,false)
   or coalesce(can_load_json_files,false)
   or coalesce(can_import_edit_drafts,false)
   or coalesce(can_submit_drafts,false);

-- Admin/Super Admin bypasses access restrictions anyway; setting these true makes
-- the stored row intuitive in exports/diagnostics.
update public.eaf_v2_staff_permissions
set can_access_apply=true,
    can_access_hr=true,
    can_access_jd_manual=true,
    can_access_hr_law=true
where coalesce(is_admin,false) or coalesce(is_super_admin,false);

-- ---------------------------------------------------------------------------
-- 2) Global application catalogue / modes.
--    Admin always bypasses these modes.
-- ---------------------------------------------------------------------------
create table if not exists public.eaf_v2_gateway_apps (
  app_code text primary key,
  app_name text not null,
  app_path text not null,
  mode text not null default 'restricted'
    check (mode in ('restricted','invitation_only','admin_only','disabled')),
  sort_order integer not null default 100,
  updated_at timestamptz not null default now(),
  updated_by uuid null
);

insert into public.eaf_v2_gateway_apps(app_code,app_name,app_path,mode,sort_order)
values
  ('apply','Apply Now','index.html','invitation_only',10),
  ('hr','HR Staff','hr.html','restricted',20),
  ('jd_manual','Job Description Manual','jd-manual.html','restricted',30),
  ('hr_law','Employment Act & HR Calculators','employment-act.html','restricted',40)
on conflict (app_code) do update set
  app_name=excluded.app_name,
  app_path=excluded.app_path,
  sort_order=excluded.sort_order;

alter table public.eaf_v2_gateway_apps enable row level security;
revoke all on public.eaf_v2_gateway_apps from anon;
revoke all on public.eaf_v2_gateway_apps from authenticated;
grant select on public.eaf_v2_gateway_apps to authenticated;

drop policy if exists eaf_v2_gateway_apps_authenticated_select on public.eaf_v2_gateway_apps;
create policy eaf_v2_gateway_apps_authenticated_select
on public.eaf_v2_gateway_apps
for select to authenticated
using (true);

-- ---------------------------------------------------------------------------
-- 3) Applicant invitation links for Apply Now.
-- ---------------------------------------------------------------------------
create table if not exists public.eaf_v2_gateway_invitations (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  app_code text not null default 'apply' check (app_code='apply'),
  company_code text not null check (company_code in ('meg','meh','hds','abn')),
  expires_at timestamptz not null,
  max_uses integer not null default 1 check (max_uses >= 1 and max_uses <= 1000),
  use_count integer not null default 0 check (use_count >= 0),
  created_by uuid null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz null,
  revoked_by uuid null
);

alter table public.eaf_v2_gateway_invitations enable row level security;
revoke all on public.eaf_v2_gateway_invitations from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4) Access/audit log.
-- ---------------------------------------------------------------------------
create table if not exists public.eaf_v2_gateway_access_log (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  event_code text not null,
  app_code text null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_eaf_v2_gateway_access_log_created
  on public.eaf_v2_gateway_access_log(created_at desc);
create index if not exists idx_eaf_v2_gateway_access_log_user
  on public.eaf_v2_gateway_access_log(user_id,created_at desc);

alter table public.eaf_v2_gateway_access_log enable row level security;
revoke all on public.eaf_v2_gateway_access_log from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5) Central permission helper.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_can_access(
  p_app_code text,
  p_user_id uuid default auth.uid()
)
returns boolean
language plpgsql
stable
security definer
set search_path=public,auth
as $$
declare
  v_mode text;
  v_perm boolean := false;
  v_admin boolean := false;
begin
  if auth.uid() is null or p_user_id is null or p_user_id <> auth.uid() then
    return false;
  end if;

  select coalesce(v.is_admin,false) or coalesce(v.is_super_admin,false)
    into v_admin
  from public.eaf_v2_staff_permissions v
  where v.user_id=p_user_id;

  if coalesce(v_admin,false) then return true; end if;

  select a.mode into v_mode
  from public.eaf_v2_gateway_apps a
  where a.app_code=p_app_code;

  if not found or v_mode in ('admin_only','disabled') then return false; end if;

  select case p_app_code
    when 'apply' then coalesce(v.can_access_apply,false)
    when 'hr' then coalesce(v.can_access_hr,false)
    when 'jd_manual' then coalesce(v.can_access_jd_manual,false)
    when 'hr_law' then coalesce(v.can_access_hr_law,false)
    else false
  end
  into v_perm
  from public.eaf_v2_staff_permissions v
  where v.user_id=p_user_id;

  return coalesce(v_perm,false);
end;
$$;

revoke all on function public.eaf_v2_gateway_can_access(text,uuid) from public;
grant execute on function public.eaf_v2_gateway_can_access(text,uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 6) One-call dashboard bootstrap for the signed-in user.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_my_access()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth
as $$
declare
  v_uid uuid := auth.uid();
  v_name text := '';
  v_email text := '';
  v_admin boolean := false;
  v_apps jsonb := '{}'::jsonb;
begin
  if v_uid is null then
    raise exception 'Authentication required' using errcode='42501';
  end if;

  select coalesce(s.full_name,''), coalesce(u.email,'')
    into v_name,v_email
  from auth.users u
  left join public.eaf_staff_profiles s on s.id=u.id
  where u.id=v_uid;

  select coalesce(v.is_admin,false) or coalesce(v.is_super_admin,false)
    into v_admin
  from public.eaf_v2_staff_permissions v
  where v.user_id=v_uid;

  select coalesce(jsonb_object_agg(
    a.app_code,
    jsonb_build_object(
      'name',a.app_name,
      'path',a.app_path,
      'mode',a.mode,
      'allowed',public.eaf_v2_gateway_can_access(a.app_code,v_uid)
    ) order by a.sort_order
  ),'{}'::jsonb)
  into v_apps
  from public.eaf_v2_gateway_apps a;

  return jsonb_build_object(
    'user',jsonb_build_object(
      'id',v_uid,
      'full_name',coalesce(nullif(v_name,''),v_email),
      'email',v_email,
      'is_admin',coalesce(v_admin,false)
    ),
    'apps',v_apps
  );
end;
$$;

revoke all on function public.eaf_v2_gateway_my_access() from public;
grant execute on function public.eaf_v2_gateway_my_access() to authenticated;

-- ---------------------------------------------------------------------------
-- 7) Admin directory with names + emails + gateway permissions.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_staff_directory()
returns table (
  id uuid,
  full_name text,
  email text,
  account_status text,
  is_admin boolean,
  is_super_admin boolean,
  can_access_apply boolean,
  can_access_hr boolean,
  can_access_jd_manual boolean,
  can_access_hr_law boolean
)
language plpgsql
stable
security definer
set search_path=public,auth
as $$
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;

  return query
  select
    u.id,
    coalesce(nullif(s.full_name,''),u.email,'')::text,
    coalesce(u.email,'')::text,
    case
      when u.banned_until is not null and u.banned_until > now() then 'disabled'
      when u.email_confirmed_at is null then 'pending'
      else 'active'
    end::text,
    coalesce(v.is_admin,false),
    coalesce(v.is_super_admin,false),
    coalesce(v.can_access_apply,false),
    coalesce(v.can_access_hr,false),
    coalesce(v.can_access_jd_manual,false),
    coalesce(v.can_access_hr_law,false)
  from auth.users u
  left join public.eaf_staff_profiles s on s.id=u.id
  left join public.eaf_v2_staff_permissions v on v.user_id=u.id
  where s.id is not null or v.user_id is not null
  order by lower(coalesce(nullif(s.full_name,''),u.email,'')),lower(coalesce(u.email,''));
end;
$$;

revoke all on function public.eaf_v2_gateway_staff_directory() from public;
grant execute on function public.eaf_v2_gateway_staff_directory() to authenticated;

-- ---------------------------------------------------------------------------
-- 8) Admin: per-user gateway access setter.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_set_user_access(
  p_user_id uuid,
  p_app_code text,
  p_allowed boolean
)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;
  if p_user_id is null or p_app_code not in ('apply','hr','jd_manual','hr_law') then
    raise exception 'Valid user and app code are required';
  end if;
  -- Build 10 normally seeds this row when eaf_staff_profiles is created. This
  -- defensive insert also handles any older account whose V2 row was missed.
  insert into public.eaf_v2_staff_permissions(user_id)
  select p.id from public.eaf_staff_profiles p where p.id=p_user_id
  on conflict (user_id) do nothing;

  if not exists(select 1 from public.eaf_v2_staff_permissions where user_id=p_user_id) then
    raise exception 'V2 staff permission profile not found';
  end if;

  update public.eaf_v2_staff_permissions
  set
    can_access_apply = case when p_app_code='apply' then p_allowed else can_access_apply end,
    can_access_hr = case when p_app_code='hr' then p_allowed else can_access_hr end,
    can_access_jd_manual = case when p_app_code='jd_manual' then p_allowed else can_access_jd_manual end,
    can_access_hr_law = case when p_app_code='hr_law' then p_allowed else can_access_hr_law end
  where user_id=p_user_id;

  insert into public.eaf_v2_gateway_access_log(user_id,event_code,app_code,details)
  values(auth.uid(),'permission_change',p_app_code,jsonb_build_object('target_user_id',p_user_id,'allowed',p_allowed));

  return true;
end;
$$;

revoke all on function public.eaf_v2_gateway_set_user_access(uuid,text,boolean) from public;
grant execute on function public.eaf_v2_gateway_set_user_access(uuid,text,boolean) to authenticated;

-- ---------------------------------------------------------------------------
-- 9) Admin: application-mode setter.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_set_app_mode(
  p_app_code text,
  p_mode text
)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;
  if p_app_code not in ('apply','hr','jd_manual','hr_law') then
    raise exception 'Invalid app code';
  end if;
  if p_mode not in ('restricted','invitation_only','admin_only','disabled') then
    raise exception 'Invalid app mode';
  end if;
  if p_app_code <> 'apply' and p_mode='invitation_only' then
    raise exception 'Invitation Only is currently supported for Apply Now only';
  end if;

  update public.eaf_v2_gateway_apps
  set mode=p_mode,updated_at=now(),updated_by=auth.uid()
  where app_code=p_app_code;

  insert into public.eaf_v2_gateway_access_log(user_id,event_code,app_code,details)
  values(auth.uid(),'app_mode_change',p_app_code,jsonb_build_object('mode',p_mode));
  return true;
end;
$$;

revoke all on function public.eaf_v2_gateway_set_app_mode(text,text) from public;
grant execute on function public.eaf_v2_gateway_set_app_mode(text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 10) Admin: create/list/revoke Apply Now invitation links.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_create_invitation(
  p_company_code text,
  p_expires_at timestamptz,
  p_max_uses integer default 1
)
returns table(token uuid,expires_at timestamptz,max_uses integer)
language plpgsql
security definer
set search_path=public,auth
as $$
declare
  v_token uuid := gen_random_uuid();
  v_exp timestamptz := coalesce(p_expires_at,now()+interval '7 days');
  v_max integer := greatest(1,least(coalesce(p_max_uses,1),1000));
  v_mode text;
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;
  if lower(coalesce(p_company_code,'')) not in ('meg','meh','hds','abn') then
    raise exception 'Invalid company code';
  end if;
  if v_exp <= now() then raise exception 'Expiry must be in the future'; end if;

  select mode into v_mode from public.eaf_v2_gateway_apps where app_code='apply';
  if v_mode <> 'invitation_only' then
    raise exception 'Apply Now must be in Invitation Only mode before creating applicant links';
  end if;

  insert into public.eaf_v2_gateway_invitations(token,company_code,expires_at,max_uses,created_by)
  values(v_token,lower(p_company_code),v_exp,v_max,auth.uid());

  insert into public.eaf_v2_gateway_access_log(user_id,event_code,app_code,details)
  values(auth.uid(),'invitation_created','apply',jsonb_build_object('company_code',lower(p_company_code),'expires_at',v_exp,'max_uses',v_max));

  return query select v_token,v_exp,v_max;
end;
$$;

revoke all on function public.eaf_v2_gateway_create_invitation(text,timestamptz,integer) from public;
grant execute on function public.eaf_v2_gateway_create_invitation(text,timestamptz,integer) to authenticated;

create or replace function public.eaf_v2_gateway_list_invitations()
returns table(
  id uuid,
  token uuid,
  company_code text,
  expires_at timestamptz,
  max_uses integer,
  use_count integer,
  revoked_at timestamptz,
  created_at timestamptz,
  created_by_name text
)
language plpgsql
stable
security definer
set search_path=public,auth
as $$
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;
  return query
  select i.id,i.token,i.company_code,i.expires_at,i.max_uses,i.use_count,i.revoked_at,i.created_at,
         coalesce(nullif(s.full_name,''),u.email,'')::text
  from public.eaf_v2_gateway_invitations i
  left join auth.users u on u.id=i.created_by
  left join public.eaf_staff_profiles s on s.id=i.created_by
  order by i.created_at desc
  limit 100;
end;
$$;

revoke all on function public.eaf_v2_gateway_list_invitations() from public;
grant execute on function public.eaf_v2_gateway_list_invitations() to authenticated;

create or replace function public.eaf_v2_gateway_revoke_invitation(p_invitation_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;
  update public.eaf_v2_gateway_invitations
  set revoked_at=coalesce(revoked_at,now()),revoked_by=auth.uid()
  where id=p_invitation_id;
  if not found then raise exception 'Invitation not found'; end if;

  insert into public.eaf_v2_gateway_access_log(user_id,event_code,app_code,details)
  values(auth.uid(),'invitation_revoked','apply',jsonb_build_object('invitation_id',p_invitation_id));
  return true;
end;
$$;

revoke all on function public.eaf_v2_gateway_revoke_invitation(uuid) from public;
grant execute on function public.eaf_v2_gateway_revoke_invitation(uuid) to authenticated;

-- Anonymous/authenticated bearer-token validator. No invitation table SELECT is exposed.
create or replace function public.eaf_v2_gateway_validate_invitation(p_token uuid)
returns table(
  allowed boolean,
  company_code text,
  expires_at timestamptz,
  remaining_uses integer
)
language plpgsql
stable
security definer
set search_path=public,auth
as $$
declare
  v_mode text;
  v_row public.eaf_v2_gateway_invitations%rowtype;
begin
  select mode into v_mode from public.eaf_v2_gateway_apps where app_code='apply';
  if v_mode <> 'invitation_only' then
    return query select false,null::text,null::timestamptz,0;
    return;
  end if;

  select * into v_row
  from public.eaf_v2_gateway_invitations
  where token=p_token
    and revoked_at is null
    and expires_at>now()
    and use_count<max_uses;

  if not found then
    return query select false,null::text,null::timestamptz,0;
  else
    return query select true,v_row.company_code,v_row.expires_at,greatest(0,v_row.max_uses-v_row.use_count);
  end if;
end;
$$;

revoke all on function public.eaf_v2_gateway_validate_invitation(uuid) from public;
grant execute on function public.eaf_v2_gateway_validate_invitation(uuid) to anon,authenticated;

-- Consume one use only after the application submission succeeds in the browser.
create or replace function public.eaf_v2_gateway_consume_invitation(p_token uuid)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  update public.eaf_v2_gateway_invitations
  set use_count=use_count+1
  where token=p_token
    and revoked_at is null
    and expires_at>now()
    and use_count<max_uses
    and exists(select 1 from public.eaf_v2_gateway_apps where app_code='apply' and mode='invitation_only');
  return found;
end;
$$;

revoke all on function public.eaf_v2_gateway_consume_invitation(uuid) from public;
grant execute on function public.eaf_v2_gateway_consume_invitation(uuid) to anon,authenticated;

-- ---------------------------------------------------------------------------
-- 11) Audit helpers.
-- ---------------------------------------------------------------------------
create or replace function public.eaf_v2_gateway_log_app_open(p_app_code text)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if auth.uid() is null then return false; end if;
  if not public.eaf_v2_gateway_can_access(p_app_code,auth.uid()) then return false; end if;
  insert into public.eaf_v2_gateway_access_log(user_id,event_code,app_code)
  values(auth.uid(),'app_open',p_app_code);
  return true;
end;
$$;
revoke all on function public.eaf_v2_gateway_log_app_open(text) from public;
grant execute on function public.eaf_v2_gateway_log_app_open(text) to authenticated;

create or replace function public.eaf_v2_gateway_log_login()
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if auth.uid() is null then return false; end if;
  insert into public.eaf_v2_gateway_access_log(user_id,event_code) values(auth.uid(),'login');
  return true;
end;
$$;
revoke all on function public.eaf_v2_gateway_log_login() from public;
grant execute on function public.eaf_v2_gateway_log_login() to authenticated;

create or replace function public.eaf_v2_gateway_get_access_log(p_limit integer default 100)
returns table(
  created_at timestamptz,
  full_name text,
  email text,
  event_code text,
  app_code text,
  details jsonb
)
language plpgsql
stable
security definer
set search_path=public,auth
as $$
begin
  if not public.eaf_v2_is_admin(auth.uid()) then
    raise exception 'V2 Administrator access required' using errcode='42501';
  end if;
  return query
  select l.created_at,
         coalesce(nullif(s.full_name,''),u.email,'')::text,
         coalesce(u.email,'')::text,
         l.event_code,l.app_code,l.details
  from public.eaf_v2_gateway_access_log l
  left join auth.users u on u.id=l.user_id
  left join public.eaf_staff_profiles s on s.id=l.user_id
  order by l.created_at desc
  limit greatest(1,least(coalesce(p_limit,100),500));
end;
$$;
revoke all on function public.eaf_v2_gateway_get_access_log(integer) from public;
grant execute on function public.eaf_v2_gateway_get_access_log(integer) to authenticated;

commit;
