import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role authenticated; create role anon; create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated,anon;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,banned_until timestamptz);
create table public.jd_positions(id integer primary key,title text);
insert into public.jd_positions values(1,'Existing JD fixture');
insert into auth.users values('00000000-0000-4000-8000-000000000099','existing@example.invalid',now(),null);`);
const sql=await readFile(new URL('./fixtures/staging-admin-role-bootstrap.sql',import.meta.url),'utf8');
await assert.rejects(()=>db.exec(sql),/Three dedicated active dummy/);
await db.exec('rollback');
const ids=['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003'];
for(let i=0;i<3;i++) await db.query('insert into auth.users values($1,$2,now(),null)',[ids[i],`edp-test-${['super','admin','user'][i]}@example.invalid`]);
await db.exec(sql);
assert.equal((await db.query('select count(*)::int as n from eaf_v2_staff_permissions')).rows[0].n,3);
assert.equal((await db.query('select title from jd_positions')).rows[0].title,'Existing JD fixture');
assert.equal((await db.query('select count(*)::int as n from auth.users')).rows[0].n,4);
await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[0]]);
await db.exec('set role authenticated');
assert.equal((await db.query('select count(*)::int as n from eaf_v2_gateway_staff_directory()')).rows[0].n,3);
assert.equal((await db.query('select eaf_v2_set_administrator($1,true,false) as result',[ids[2]])).rows[0].result,true);
assert.equal((await db.query('select eaf_v2_set_administrator($1,false,true) as result',[ids[2]])).rows[0].result,false);
assert.equal((await db.query("select count(*)::int as n from eaf_v2_gateway_get_access_log(100) where event_code='administrator_role_change'")).rows[0].n,2);
await db.exec('reset role; set role anon');
await assert.rejects(()=>db.query('select eaf_v2_gateway_staff_directory()'),e=>e.code==='42501');
await db.exec('reset role');
await assert.rejects(()=>db.exec(sql),/EAF tables already exist/);
await db.exec('rollback');
await db.close();
console.log('PASS: staging bootstrap prerequisites, dummy-only seeding, JD/existing-user preservation, directory, role RPCs, audit, anonymous denial and overwrite refusal.');
